### ISSUE TITLE
Obligations of Partner Codes

### ISSUE THREAD

**Issue by loriab** [MolSSI/QC_JSON_Schema#1]
Should there be lists of light to full obligations for partner codes, both on the JSON-producing and JSON-consuming side?

for example,
* outputs QM portion of Molecule into JSON (QC program)
* can run a geometry optimization from a JSON input (QC program)
* tests its JSON input/output alongside usual testing scheme (ALL)
* plots orbitals from JSON schema basis sets and densities (Viz program)
* returns JSON vibrational modes from JSON Hessian (vibrational analysis program)

**Comment by cryos** [comment]
It would be great to develop a notion on the level of support offered, maybe basic, intermediate, advanced, and complete or similar.

**Comment by dgasmith** [comment]
I like the idea of constructing a list of thing that a program must, do and then attaching them to tiers. Something like:
 - A: Verifies input JSON for completeness
 - B: Exports energy/gradient/Hessian quantities
 - C: Runs QM "workflows" (optimization, response, spectra, etc)
 - D: Exports Wavefunction quantities (orbitals, eigenvalues, densities)
 - E: Convert atomic-orbital quantities to a common representation
 - F: Adhere to a common set of input and output variables

To meet the various levels of interoperability QM programs must do:
Level 1 - A, B, C
Level 2 - A, B, C, F
Level 3 - A, B, C, D, E, F

The two definition approach could be useful as some programs could offer items of their "interoperability level".

**Comment by cryos** [comment]
This sounds like the right direction to me, maybe reorder so that each level is ABC, ABCD, ABCDEF :-)
