### ISSUE TITLE
Counting starts from 0 or 1?

### ISSUE THREAD

**Issue by tovrstra** [MolSSI/QC_JSON_Schema#13]
When refering to array elements, e.g. an atom or a center index, we should decide that counting starts either from 0 (please) or 1 (noooo). Some is already mentioned here: [Technical_Specifications.md](../blob/master/Technical_Specifications.md#how-do-we-reference-other-objects)

For example, it is relevant to #12.

**Comment by dgasmith** [comment]
Agreed, count from zero! I wonder how that translates to Fortran JSON parsers. @wadejong any comments?

**Comment by dgasmith** [comment]
@tovrstra Where do you think the best place to put this information is, in a FAQ?

**Comment by tovrstra** [comment]
Mentioning it in the FAQ is certainly helpful but we should probably also have a more formal definition of such rules. I'm not very familiar with [JSON Schema](http://json-schema.org). If we eventually write out such a schema, which would facilitate validation, it can also be fixed formally, see e.g. http://json-schema.org/examples.html

**Comment by cryos** [comment]
I think starting from 0 makes sense, JSON arrays generally do this. It should go in the FAQ.
