### ISSUE TITLE
Suggestion: rename variables to results

### ISSUE THREAD

**Issue by tovrstra** [MolSSI/QC_JSON_Schema#14]
It is probably just me but `variables` is an odd name for results of a calculation. These results are by definition not variable once you receive the output of a calculation.

**Comment by dgasmith** [comment]
The `return_result` is the answer that you request to make things simpler down the line. Should variables be `results` and include the `return_result` to make things clear?

**Comment by tovrstra** [comment]
Renaming `variables` to `results` would be one way to go but lets wait for other suggestions too.
The `return_value` field can certainly stay because many drivers have one primary result, e.g. an energy. It would be helpful to include the return value in the `results` with its proper name, e.g. to have a `energy` field in `results` as well.

**Comment by dgasmith** [comment]
We have switched this around a bit where `variables` is now `properties` based on recommendations from the workshop.
