### ISSUE TITLE
Suggestion: support for YAML file format

### ISSUE THREAD

**Issue by adabbott** [MolSSI/QC_JSON_Schema#36]
YAML files, like JSONs, translate directly into hierarchies of key/value pairs. However, YAMLs offer superior human-readability compared to JSONs. Why not allow the option for YAML-style inputs and outputs? This may be preferred for users who choose to interact directly with input and output files.

**Comment by langner** [comment]
I think YAML has some great features missing from JSON (anchors, comments, readability as you mention). On the other hand, JSON is probably more widespread and the parsers are faster at this point.

Also, YAML is a superset (well, almost) of JSON, so there shouldn't be a problem converting JSONs to YAML, or moving the YAML in the future if that seems like the way to go.

**Comment by sunqm** [comment]
YAML support sounds a bad idea for me at the moment.  Adding the YAM support may lead to another dimension of complexity.  I assume the JSON format serves as intermediate data for different QC program to communicate.  I guess human readability should be less concerned although to some extent JSON is readable.

**Comment by dgasmith** [comment]
Hmm, is there any reason that this cannot be an optional input for programs who choose to implement a YAML reader? As @langner mentioned if we focus on a JSON spec, the spec itself is representable in YAML without data loss and the end structure should be the same once imported to the language of your choice.

In Python using `yaml.read` vs `json.read` is all that would be required.

**Comment by loriab** [comment]
I've played with both and really like yaml. Right now I have about quarter-and-three-quarter yaml and json. Insofar as it's dump/load simple, I plan to support yaml wherever potentially user-facing fields overlap with the JSON schema.

**Comment by dgasmith** [comment]
The short answer here is "yes". Any format which supports the basic required quantities (hierarchical key- value/array) support is valid such as JSON/YAML/XML/HDF5/etc. However, this is up to the individual programs to add parsers for these formats or not. Keeping in mind JSON is the "officially" supported language at the moment.
