### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QC_JSON_Schema#47]
I have started implementing this schema into several QM packages and external geometry optimizers to get a better handle on what we can currently do, what are the issues, and what are the (many) additional fields we need to add. 

So that other software can have something stable to complete the handshake, I would like to mint a "Version 1" of the schema this month. While particularly lacking on the visualization and atomic orbital quantities, the record of energies and gradients is still quite useful for many applications. 

Are there objection to this or fields that we must add before a "beta" release?

**Comment by loriab** [comment]
Sounds good. By the 14th would be handy so as to change all the 0 --> 1 for the next Psi4 release.

**Comment by dgasmith** [comment]
Merged, closing.
