### ISSUE TITLE
Starter FAQ

### ISSUE THREAD

**Issue by loriab** [MolSSI/QC_JSON_Schema#6]
Answers by DGAS

1. _Will the json be validated before it reaches me?_ 
No, but we will provide a library.

2. _Is MolSSI the validation gatekeeper?_
Yes

3. _Can I add extra fields if my software piece needs internal extensions?_
Absolutely (any non-taken field is valid)

4. _Will this be broad enough that we can actually abandon [annoying-but-widespread-file-format] files like xyz, molden, mol2?_
Hopefully

5. _Are there libraries for writing this in [language]?_
No, we we will only supply libraries for Python/C++

**Comment by saromleang** [comment]
> 5.  Are there libraries for writing this in [language]?
   No, we we will only supply libraries for Python/C++

So to be clear - Fortran will not be a supported language?

**Comment by dgasmith** [comment]
Saying that it is not supported is a stretch. This is a spec, it doesn't particularly matter how the data ends up in this form. I have yet to find a decent JSON library in Fortran that is not 2008+.

**Comment by tovrstra** [comment]
> 3. *Can I add extra fields if my software piece needs internal extensions?*
>    Absolutely (any non-taken field is valid)

That is dangerous. When extending the schema later, old JSON files may become incompatible with the new version of the schema, e.g. when they use fields that suddenly become reserved in the new version. You really want to limit "internal extensions" to parts of the schema that are specifically dedicated to it.

**Comment by tovrstra** [comment]
@dgasmith Another question for the FAQ: should the spec be designed in such a way that JSON files are easily made human-readable and/or human-writeable? Or is it meant processing by software only?

**Comment by dgasmith** [comment]
@tovrstra I think that we should endeavor for the minimal input (molecule and brief method spec) and output to be human read/writable. However, when it comes to saving orbitals and the like I don't think this will hold true for very long.
